// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CountriesDB.Models;

public partial class Country
{
    public int CountryId { get; set; }

    public string Acronym { get; set; }

    public string CountryName { get; set; }

    public string Phonecode { get; set; }
}